import Head from "next/head";
import Hero from '@/components/hero';
import About from "@/components/about";
import Skills from '@/components/skills';
import Projects from '@/components/projects';
import Contact from '@/components/contact';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Hero/>
        <About/>
        <Skills />
        <Projects />
        <Contact />
      </div>
    </>
  );
}
